spring.application.name: bikini-validation

server.port: 8081

kafka:
  enabled: true
  topic: bikini-checks
  server: localhost:29092
  clientId: client_id

spring.data.mongodb:
  host: localhost
  port: 27017
  database: test
  username: admin
  password: admin
  authentication-database: admin

management:
  endpoints:
    web:
      exposure:
        include: health,prometheus
  metrics:
    export:
      prometheus:
        enabled: true
    distribution:
      percentiles-histogram:
        "[http.server.requests]": true